config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :customers
  namespace :admin do
    root 'homes#top' 
    resources :items
    resources :genres
    resources :customers
    resources :orders
    resources :order_details
    get 'sign_in' =>'admins/sessions#new'
  end
  namespace :public do
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :items, only: [:index, :show]
    get 'orders/thanks' => 'orders#thanks'
    resources :orders, only: [:index, :show, :new, :update, :create]
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get 'customers/edit' => 'customers#edit'
    get 'customers/my_page' => 'customers#show'
    get 'customers/checks' => 'customers#checks'
    patch 'customers' => 'customers#update'
    patch 'customers/quit' => 'customers#quit'
    get 'homes' => 'homes#top'
    get 'homes/about' => 'homes#about'
    post 'orders/checks' => 'orders#checks'
    delete 'cart_items' => 'cart_items#destroy_all'
    root 'homes#top'
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :cart_items
  has_many :addresses
  has_many :orders
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def active_for_authentication?
    super && (is_active == true)
  end
  def full_address
    '〒' + postal_code + ' ' + address + '   '
  end
  def full_name
  first_name + ' ' + last_name
  end
  validates :encrypted_password, length: { minimum: 6 }
     
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
    
    def show
        @customers = Customer.all
        @customer = Customer.find(params[:id])
    end
    
    def index
        @customers = Customer.page(params[:page]).per(10)
    
    end
    
    def edit
        @customer = Customer.find(params[:id])
    end
    
    def update
        @customer = Customer.find(params[:id])
        if @customer.update(customer_params)
           redirect_to admin_customer_path(@customer)
        else
           render :edit   
        end
    end
    private
    def customer_params
        params.require(:customer).permit(:last_name, :last_name_kana, :first_name, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_active)
    end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div>
<h2>会員情報編集</h2>
<%= form_with model: @customer, url: admin_customer_path, local:true do |f| %>
<table>
  <tbody>
   
      <tr>
       <td>
        氏名
       </td>
       <td>
        <%= f.text_area :first_name %><%= f.text_area :last_name %>  
       </td>
      </tr>
      <tr>
       <td>
        フリガナ
       </td>
       <td>
          <%= f.text_area :first_name_kana %><%= f.text_area :last_name_kana %>
       </td>
      </tr>
      <tr>
       <td>
        郵便番号
       </td>
       <td>
         <%= f.text_area :postal_code %>  
       </td>
      </tr>
      <tr>
       <td>
        住所
       </td>
       <td>
          <%= f.text_area :address %> 
       </td>
      </tr>
      <tr>
       <td>
        電話番号
       </td>
       <td>
          <%= f.text_area :telephone_number %> 
       </td>
      </tr>
      <tr>
       <td>
        メールアドレス
       </td>
       <td>
          <%= f.text_area :email %> 
       </td>
      </tr>
      <tr>
       <td>
        会員ステータス
       </td>
       <td>
          <%= f.radio_button :is_active, "true" %> 
          <%= f.label :is_active, "有効" %>
          <%= f.radio_button :is_active, "false" %> 
          <%= f.label :is_active, "退会" %>
       </td>
      </tr>
  </tbody>
  </table>
  <%= f.submit "変更を保存" %>
  <% end %>
  </div>

app/views/admin/customers/index.html.erb
<div>
<h2>会員一覧</h2>

<table>
  <thead>
    <tr>
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
    </tr>
  </thead>
<% @customers.each do |customer| %>
  <tbody>
    <td><%= customer.id %></td>
    <td><%= link_to customer.full_name, admin_customer_path(customer) %></td>
    <td><%= customer.email %></td>
    <td><%= customer.is_active %></td>
  </tbody>
<% end %>
</table>

<%= paginate @customers %>
</div>

app/views/admin/customers/show.html.erb
<div>
 <h2>マイページ</h2>

 <table>
  <tbody>
      <tr>
       <td>
        氏名
       </td>
       <td>
        <%= @customer.first_name %> <%= @customer.last_name %>  
       </td>
      </tr>
      <tr>
       <td>
        カナ
       </td>
       <td>
          <%= @customer.first_name_kana %> <%= @customer.last_name_kana %>
       </td>
      </tr>
      <tr>
       <td>
        郵便番号
       </td>
       <td>
         <%= @customer.postal_code %>  
       </td>
      </tr>
      <tr>
       <td>
        住所
       </td>
       <td>
          <%= @customer.address %> 
       </td>
      </tr>
      <tr>
       <td>
        電話番号
       </td>
       <td>
          <%= @customer.telephone_number %> 
       </td>
      </tr>
      <tr>
       <td>
        メールアドレス
       </td>
       <td>
          <%= @customer.email %> 
       </td>
      </tr>
  </tbody>
  </table>
  <div>
      <a><%= link_to "編集する" , edit_admin_customer_path(@customer) %></a>
      <a><%= link_to "注文履歴一覧" , admin_orders_path %></a>
  </div>
  </div>