config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :customers
  namespace :admin do
    root 'homes#top' 
    resources :items
    resources :genres
    resources :customers
    resources :orders
    resources :order_details
    get 'sign_in' =>'admins/sessions#new'
  end
  namespace :public do
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :items, only: [:index, :show]
    get 'orders/thanks' => 'orders#thanks'
    resources :orders, only: [:index, :show, :new, :update, :create]
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get 'customers/edit' => 'customers#edit'
    get 'customers/my_page' => 'customers#show'
    get 'customers/checks' => 'customers#checks'
    patch 'customers' => 'customers#update'
    patch 'customers/quit' => 'customers#quit'
    get 'homes' => 'homes#top'
    get 'homes/about' => 'homes#about'
    post 'orders/checks' => 'orders#checks'
    delete 'cart_items' => 'cart_items#destroy_all'
    root 'homes#top'
  end
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
    def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :customer
    def subtotal
        item.add_tax_price*amount
    end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :cart_items
  has_many :addresses
  has_many :orders
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def active_for_authentication?
    super && (is_active == true)
  end
  def full_address
    '〒' + postal_code + ' ' + address + '   '
  end
  def full_name
  first_name + ' ' + last_name
  end
  validates :encrypted_password, length: { minimum: 6 }
     
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :genre, optional: true
    has_many :cart_items
    has_many :order_details
    attachment :image
    validates :price, presence: true
    
    def add_tax_price
        (price*1.10).floor
    end
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_many :order_details
    enum payment_method: { credit_card: 0, transfer: 1 }
    enum status: { wait: 0, check: 1, make: 2, standby:3, ship: 4}
    def full_address
      '〒' + postal_code + ' ' + address + '   '
    end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item
    enum is_active: { stop: 0, wait: 1, make: 2, comp: 3}
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
    def index
        @genre = Genre.new
        @genres = Genre.all
    end
    
    def create
        @genres = Genre.all
        @genre = Genre.new(genre_params)
        @genre.save
        redirect_to admin_genres_path
    end
    
    def edit
        @genres = Genre.all
        @genre = Genre.find(params[:id])
    end
    
    def update
        @genre = Genre.find(params[:id])
        if @genre.update(genre_params)
           redirect_to admin_genres_path
        else
           render :edit
        end
    end
   private
   def genre_params
       params.require(:genre).permit(:name)
   end
    
    
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    def top
       @orders = Order.page(params[:page]).per(10)
    end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    def index
        @items = Item.page(params[:page]).per(10)
        @genres = Genre.all
    end
    
    def new
        @item = Item.new
        @genres = Genre.all
        @items = Item.all
    end
    
    def create
        @items = Item.all
        @genres = Genre.all
        @item = Item.new(item_params)
        if @item.save!
          redirect_to admin_item_path(@item.id)
        else
          render :index
        end
    end
    
    def show
        @item = Item.find(params[:id])
    end
    
    def edit
        @item = Item.find(params[:id])
        @genres = Genre.all
    end
    
    def update
        @item = Item.find(params[:id])
        if @item.update(item_params)
           redirect_to admin_item_path(@item)
        else
           render :edit
        end
    end
    private
    def item_params
        params.require(:item).permit(:name, :image, :introduction, :price, :genre_id, :is_active)
    end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    def show
        @order = Order.find(params[:id])
        @order_details = @order.order_details
        @order_detail = OrderDetail.find_by(order_id: @order)
    end 
    def update
        @order = Order.find(params[:id])
        @order.update(order_params)
        redirect_to admin_order_path(@order)
    end
   private
    def order_params
        params.require(:order).permit(:customer_id, :payment_method, :total_payment, :address, :postal_code, :name, :shipping_cost, :status)
    end
    def order_detail_params
         params.permit(:order_id, :item_id, :amount, :price, :is_active)
    end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
 before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
      if current_admin
        admin_root_path
      else
        public_customers_my_page_path
      end
  end
  def after_sign_out_path_for(resource)
    if resource == :customer
      public_homes_path
    else
      new_admin_session_path
    end
  end
  protected
  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email])
    if @customer 
      if @customer.valid_password?(params[:customer][:password]) && (@customer.is_active == false)
        flash[:cust] = "退会済みです。再度ご登録をしてご利用ください。"
        redirect_to new_customer_registration_path
      else
        flash[:cust] = "項目を入力してください"
      end
    end
  end
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
    private
     def cart_item_params
      params.require(:cart_item).permit(:item_id, :amount)
     end
     
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div>
<h2>ジャンル編集</h2><a class = "itemplus",
<div>
    <%= form_with model:@genre, url: admin_genre_path, local:true do |f| %>
　　<div>
　　  <%= f.label :ジャンル名 %>
      <%= f.text_field :name, autofocus: true %>
　　</div> 
　　<div>
　　<%= f.submit "変更を保存" %>
　　</div>
　　<% end %>
</div>
</div>

app/views/admin/genres/index.html.erb
<div>
<h2>ジャンル一覧・追加</h2>
<div>
    <%= form_with model:@genre, local:true, url: admin_genres_path do |f| %>
　　<div>
　　  <%= f.label :ジャンル名 %>
      <%= f.text_field :name %>
　　  <%= f.submit "新規登録" %>
　　</div>
　　<% end %>
</div>

<table>
  <thead>
    <tr>
      <th>ジャンル</th>
      <th></th>
    </tr>
  </thead>
　<% @genres.each do |genre| %>
   <tbody>
      <td>
        <%= genre.name %>
      </td>
      <td>
        <%= link_to "編集する", edit_admin_genre_path(genre.id) %>
      </td>
   </tbody>
  <% end %>
</table>
</div>

app/views/admin/items/edit.html.erb
<div>
<h2>商品編集</h2>
<%= form_with model:@item, url: admin_item_path, local:true do |f| %>
<div>
    商品画像<%= f.attachment_field :image %>
</div>
<div>

      商品名 <%= f.text_area :name %> 

</div>
<div>

      商品説明 <%= f.text_area :introduction %> 

</div>
<div>
      ジャンル  <%= f.select :genre_id, options_from_collection_for_select(@genres, :id, :name) %>
</div>
<div>

      税抜価格  <%= f.text_area :price %>円
    </h1>
</div>
<div>
      
      <%= f.radio_button :is_active, "true" %> 
      <%= f.label :is_active, "販売中" %>
      <%= f.radio_button :is_active, "false" %>
      <%= f.label :is_active, "販売停止" %>
</div>
<div>
    <%= f.submit '変更を保存' %>
</div>
<% end %>
</div>

app/views/admin/items/index.html.erb
<div>
  <div>
    <h2>商品一覧</h2><%= link_to '新規登録'  , new_admin_item_path %>
  </div>


<table>
  <thead>
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜き価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
  </thead>
<% @items.each do |item| %>
  <tbody>
    <td><%= item.id %></td>
    <td><%= link_to item.name, admin_item_path(item.id) %></td>
    <td><%= item.price %></td>
    <td><%= item.genre.name %></td>
    <td><%= item.is_active %></td>
  </tbody>
<% end %>
</table>

<%= paginate @items %>
</div>

app/views/admin/items/new.html.erb
<div>
<h2>商品新規登録</h2>
<div>
    <%= form_with model: @item , url: admin_items_path, local: true do |f| %>
    <div>
      <%= f.attachment_field :image %>
    </div>
　　<div>
　　  <%= f.label :商品名 %>
      <%= f.text_field :name %>
　　</div>
　　<div>
　　  <%= f.label :商品説明 %>
      <%= f.text_field :introduction %>
　　</div>
　　<div>
　　  <%= f.label :ジャンル %>
      <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %>
　　</div>
　　<div>
　　    <%= f.label :税抜価格 %>
　　    <%= f.text_field :price %>円
　　</div>
　　<div>
　　      <%= f.radio_button :is_active, "true" %>
　　      <%= f.label :is_active, "販売中" %>
　　      <%= f.radio_button :is_active, "false" %>
　　      <%= f.label :is_active, "販売停止" %>
　　      
　　</div>
　　<%= f.submit "新規登録" %>
　　<% end %>
</div>
</div>

app/views/admin/items/show.html.erb
<div>
<h2>商品詳細</h2>
<div>
    <a>
     <%= attachment_image_tag @item, :image , :size => '400x400' %>
    </a>
</div>
<div>
   商品名<%= @item.name %> 
</div>
<div>
   商品説明<%= @item.introduction %> 
</div>
<div>
    ジャンル<%= @item.genre.name %>
</div>
<div>
   税込価格(税抜価格)<%= @item.add_tax_price %> (<%= @item.price %>)円
</div>
<div>
   販売ステータス<%= @item.is_active %> 
</div>
<div>
   <%= link_to "編集する", edit_admin_item_path(@item.id) %> 
</div>
</div>

app/views/admin/orders/show.html.erb
<div>
    <h2>
       注文履歴詳細 
    </h2>
    <div>
    <table>
     <tr><th>購入者</th></th><td><%= @order.customer.full_name %></td></tr>
     <tr><th>注文日</th><td><%= @order.created_at %></td></tr>
     <tr><th>配送先</th><td><%= @order.full_address %></br><%= @order.name %></td></tr>
     <tr><th>支払方法</th><td><%= @order.payment_method_i18n %></td></tr>
     <%= form_with model:@order, url: admin_order_path, local:true, method: :patch do |f| %>
     <tr><th>注文ステータス</th><td><%= f.select :status, [['入金待ち',Order.statuses.key(0)],['入金確認',Order.statuses.key(1)], ['制作中',Order.statuses.key(2)], ['発送準備中',Order.statuses.key(3)],['発送済み',Order.statuses.key(4)]] %><%= f.submit "更新する" %></td></tr>
     
     <% end %>
    </table> 
        
    </div>
<div>
<table>
 <thead>
    <tr>
      <th>商品名</th>
      <th>単価(税込)</th>
      <th>数量</th>
      <th>小計</th>
      <th>製作ステータス</th>
      <th></th>
    </tr>
  </thead>
  <% @order_details.each do |order_detail| %>
  <tbody>
      
      <tr>
        <td><%= order_detail.item.name %></td>
        <td><%= order_detail.price %></td>
        <td>
          <%= order_detail.amount %>
        </td>
        <td><%= (order_detail.price*order_detail.amount) %></td>
        <%= form_with model:@order_detail, url: admin_order_detail_path, local:true, method: :patch do |f| %>
        <td><%= f.select :is_active, [['着手不可',OrderDetail.is_actives.key(0)],['製作待ち',OrderDetail.is_actives.key(1)], ['制作中',OrderDetail.is_actives.key(2)], ['製作完了',OrderDetail.is_actives.key(3)]] %></td>
        <td><%= f.submit "更新する" %></td>
        <% end %>
      </tr>
     
  </tbody>
  <% end %>
</table>
  <strong>商品合計</strong><%= @order.total_payment %>円</br>
  <strong>送料</strong><%= @order.shipping_cost %>円</br>
  <strong>請求金額合計</strong><%= (@order.total_payment+@order.shipping_cost) %>円</br>
</div>
</div>