config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :customers
  namespace :admin do
    root 'homes#top' 
    resources :items
    resources :genres
    resources :customers
    resources :orders
    resources :order_details
    get 'sign_in' =>'admins/sessions#new'
  end
  namespace :public do
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :items, only: [:index, :show]
    get 'orders/thanks' => 'orders#thanks'
    resources :orders, only: [:index, :show, :new, :update, :create]
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get 'customers/edit' => 'customers#edit'
    get 'customers/my_page' => 'customers#show'
    get 'customers/checks' => 'customers#checks'
    patch 'customers' => 'customers#update'
    patch 'customers/quit' => 'customers#quit'
    get 'homes' => 'homes#top'
    get 'homes/about' => 'homes#about'
    post 'orders/checks' => 'orders#checks'
    delete 'cart_items' => 'cart_items#destroy_all'
    root 'homes#top'
  end
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
    def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :customer
    def subtotal
        item.add_tax_price*amount
    end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :cart_items
  has_many :addresses
  has_many :orders
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def active_for_authentication?
    super && (is_active == true)
  end
  def full_address
    '〒' + postal_code + ' ' + address + '   '
  end
  def full_name
  first_name + ' ' + last_name
  end
  validates :encrypted_password, length: { minimum: 6 }
     
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :genre, optional: true
    has_many :cart_items
    has_many :order_details
    attachment :image
    validates :price, presence: true
    
    def add_tax_price
        (price*1.10).floor
    end
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_many :order_details
    enum payment_method: { credit_card: 0, transfer: 1 }
    enum status: { wait: 0, check: 1, make: 2, standby:3, ship: 4}
    def full_address
      '〒' + postal_code + ' ' + address + '   '
    end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item
    enum is_active: { stop: 0, wait: 1, make: 2, comp: 3}
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    def top
       @orders = Order.page(params[:page]).per(10)
    end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    def index
        @items = Item.page(params[:page]).per(10)
        @genres = Genre.all
    end
    
    def new
        @item = Item.new
        @genres = Genre.all
        @items = Item.all
    end
    
    def create
        @items = Item.all
        @genres = Genre.all
        @item = Item.new(item_params)
        if @item.save!
          redirect_to admin_item_path(@item.id)
        else
          render :index
        end
    end
    
    def show
        @item = Item.find(params[:id])
    end
    
    def edit
        @item = Item.find(params[:id])
        @genres = Genre.all
    end
    
    def update
        @item = Item.find(params[:id])
        if @item.update(item_params)
           redirect_to admin_item_path(@item)
        else
           render :edit
        end
    end
    private
    def item_params
        params.require(:item).permit(:name, :image, :introduction, :price, :genre_id, :is_active)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
 before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
      if current_admin
        admin_root_path
      else
        public_customers_my_page_path
      end
  end
  def after_sign_out_path_for(resource)
    if resource == :customer
      public_homes_path
    else
      new_admin_session_path
    end
  end
  protected
  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email])
    if @customer 
      if @customer.valid_password?(params[:customer][:password]) && (@customer.is_active == false)
        flash[:cust] = "退会済みです。再度ご登録をしてご利用ください。"
        redirect_to new_customer_registration_path
      else
        flash[:cust] = "項目を入力してください"
      end
    end
  end
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
    private
     def cart_item_params
      params.require(:cart_item).permit(:item_id, :amount)
     end
     
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
  <% if admin_signed_in? %>
    <div class="header">
      <div class="header-logo">
         <div class="head-list">
          <h2><%= link_to NaganoCake , public_root_path %></h2>
         </div>
      </div>
      <div class="header-navber">
        <div class="header-navicon">
         <ul class="nav-icon">
          <li class="nav-list"><%= link_to "商品一覧", admin_items_path %></li>
          <li class="nav-list"><%= link_to "会員一覧", admin_customers_path %></li>
          <li class="nav-list"><%= link_to "注文履歴", admin_root_path %></li>
          <li class="nav-list"><%= link_to "ジャンル一覧", admin_genres_path %></li>
          <li class="nav-list"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete %></li>
         </ul>
        </div>
        <div class="header-navsearch">
          <p>検索</p>

        </div>
      </div>
    </div>
    <% elsif customer_signed_in? %>
    <div class="header">
      <div class="header-logo">
         <div class="head-list">
          <h2><%= link_to NaganoCake , public_root_path %></h2>
         </div>
      </div>
      <div>
        ようこそ<%= current_customer.first_name %>さん！
      </div>
      <div class="header-navber">
        <div class="header-navicon">
         <ul class="nav-icon">
          <li class="nav-list"><%= link_to "マイページ", public_customers_my_page_path %></li>
          <li class="nav-list"><%= link_to "商品一覧", public_items_path %></li>
          <li class="nav-list"><%= link_to "カート", public_cart_items_path %></li>
          <li class="nav-list"><%= link_to"ログアウト", destroy_customer_session_path, method: :delete %></li>
         </ul>
        </div>
        <div class="header-navsearch">
          <p>検索</p>

        </div>
      </div>
    </div>
    <% else %>
    <div class="header">
      <div class="header-logo">
         <div class="head-list">
          <h2><%= link_to NaganoCake , public_root_path %></h2>
         </div>
      </div>
      <div class="header-navber">
        <div class="header-navicon">
         <ul class="nav-icon">
          <li class="nav-list"><%= link_to "About", public_homes_about_path %></li>
          <li class="nav-list"><%= link_to "商品一覧", public_items_path %></li>
          <li class="nav-list"><%= link_to "新規登録", new_customer_registration_path %></li>
          <li class="nav-list"><%= link_to "ログイン", new_customer_session_path %></li>
         </ul>
        </div>
        <div class="header-navsearch">
          <p>検索</p>

        </div>
      </div>
    </div>
    <% end %>
    </header>
    <div class="main">
      <%= yield %>
    </div>
    <div class="footer">
      
    </div>
    
  </body>
</html>